import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--color-bg)",
    padding: 24,
  },
  card: {
    width: "100%",
    maxWidth: 400,
    background: "var(--color-card)",
    borderRadius: 24,
    padding: "40px 32px",
    boxShadow: "0 8px 48px rgba(99, 102, 241, 0.10)",
    border: "1px solid var(--color-border)",
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 24,
  },
  logoIcon: { width: 36, height: 36, borderRadius: 9, objectFit: "cover" },
  logoText: {
    fontSize: 22,
    fontWeight: 700,
    background: "linear-gradient(90deg, #6366F1, #F59E0B)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  steps: {
    display: "flex",
    alignItems: "center",
    marginBottom: 28,
  },
  step: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: "var(--color-bg-elevated)",
    border: "1.5px solid var(--color-border-strong)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--color-text-muted)",
  },
  stepDone: {
    background: "var(--color-primary)",
    border: "none",
    color: "#fff",
  },
  stepActive: {
    background: "var(--color-primary-light)",
    border: "2px solid var(--color-primary)",
    color: "var(--color-primary)",
  },
  stepLine: {
    flex: 1,
    height: 1.5,
    background: "var(--color-border)",
  },
  heading: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 6,
    color: "var(--color-text)",
  },
  subtext: {
    fontSize: 15,
    color: "var(--color-text-secondary)",
    marginBottom: 28,
    lineHeight: 1.5,
  },
  errorBox: {
    background: "#FEF2F2",
    border: "1px solid #FECACA",
    borderRadius: 10,
    padding: "12px 14px",
    color: "#DC2626",
    fontSize: 14,
    marginBottom: 16,
  },
  atSign: {
    position: "absolute",
    left: 14,
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: 16,
    fontWeight: 700,
    color: "var(--color-primary)",
    pointerEvents: "none",
  },
  handleInput: {
    width: "100%",
    padding: "13px 14px 13px 30px",
    border: "1.5px solid var(--color-border-strong)",
    borderRadius: 12,
    fontSize: 16,
    fontWeight: 600,
    color: "var(--color-text)",
    background: "#FAFAFA",
    outline: "none",
    display: "block",
    transition: "border-color 0.15s, box-shadow 0.15s",
    letterSpacing: "0.01em",
  },
  hint: {
    fontSize: 13,
    color: "var(--color-text-muted)",
    marginBottom: 20,
    marginTop: 6,
  },
  submitBtn: {
    width: "100%",
    padding: "13px 16px",
    background: "linear-gradient(135deg, #6366F1, #7C3AED)",
    border: "none",
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 600,
    color: "#fff",
    display: "block",
    textAlign: "center",
    transition: "opacity 0.15s",
  },
  skipHint: {
    marginTop: 16,
    fontSize: 12,
    color: "var(--color-text-muted)",
    textAlign: "center",
  },
};