import type React from "react";

/* ─── Phone mockup styles ─────────────────────────────────────────────────── */

export const pm: Record<string, React.CSSProperties> = {
  wrap: {
    position: "relative",
    display: "flex",
    justifyContent: "center",
    paddingBottom: 34,
  },
  frame: {
    position: "relative",
    width: "min(352px, 88vw)",
    maxWidth: "100%",
    aspectRatio: "352 / 700",
    borderRadius: 48,
    background: "#FFFDFE",
    border: "6px solid #14151B",
    boxShadow: "0 34px 80px rgba(8, 21, 62, 0.18), 0 2px 0 rgba(255,255,255,0.5) inset, 0 0 0 1px rgba(17,24,39,0.05)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  statusBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 24px 0",
  },
  time: {
    fontSize: 14,
    fontWeight: 700,
    color: "#111",
    fontVariantNumeric: "tabular-nums",
  },
  statusIcons: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  island: {
    position: "absolute",
    top: 12,
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 20,
    width: 108,
    height: 29,
    borderRadius: 15,
    background: "#0D0D1A",
  },
  screen: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
    background: "#fff",
  },
  splashImage: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center",
  },
  glow: {
    position: "absolute",
    bottom: -14,
    left: "50%",
    transform: "translateX(-50%)",
    width: 320,
    height: 42,
    borderRadius: "50%",
    background: "rgba(167, 139, 250, 0.24)",
    filter: "blur(20px)",
    pointerEvents: "none",
  },
};

/* ─── Page styles ─────────────────────────────────────────────────────────── */

export const s: Record<string, React.CSSProperties> = {
  root: {
    minHeight: "100vh",
    background: "linear-gradient(180deg, #FFFFFF 0%, #FFF9FF 42%, #FBF5FF 100%)",
    color: "#111827",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', sans-serif",
    overflowX: "hidden",
  },

  /* Nav */
  nav: {
    position: "relative",
    zIndex: 50,
    maxWidth: 1440,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "28px 48px 0",
    height: 84,
    background: "transparent",
  },
  logoWrap: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    textDecoration: "none",
  },
  logoText: {
    fontSize: 23,
    fontWeight: 800,
    color: "#0C183E",
    letterSpacing: "-0.02em",
  },
  navLinks: {
    display: "flex",
    gap: 36,
    position: "absolute",
    left: "50%",
    transform: "translateX(-50%)",
  },
  navLink: {
    fontSize: 15,
    color: "#131B3F",
    textDecoration: "none",
    fontWeight: 500,
    transition: "color 0.15s",
  },
  navActions: { display: "flex", alignItems: "center", gap: 24 },
  loginLink: {
    fontSize: 15,
    color: "#111827",
    textDecoration: "none",
    fontWeight: 500,
  },
  signupBtn: {
    fontSize: 15,
    color: "#fff",
    textDecoration: "none",
    fontWeight: 700,
    background: "linear-gradient(135deg, #4F46E5 0%, #4338CA 100%)",
    padding: "14px 28px",
    borderRadius: 18,
    boxShadow: "0 10px 24px rgba(79,70,229,0.22)",
  },

  /* Hero — two column */
  hero: {
    position: "relative",
    maxWidth: 1440,
    margin: "0 auto",
    padding: "42px 48px 96px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    alignItems: "start",
    gap: 48,
    minHeight: "calc(100vh - 84px)",
    isolation: "isolate",
  },
  heroScene: {
    position: "absolute",
    left: "50%",
    bottom: 0,
    width: "100vw",
    transform: "translateX(-50%)",
    zIndex: 0,
    pointerEvents: "none",
  },
  heroSceneImage: {
    width: "100%",
    height: "auto",
    display: "block",
  },
  heroLeft: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    position: "relative",
    zIndex: 2,
    maxWidth: 560,
    paddingTop: 30,
  },
  heroRight: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    position: "relative",
    zIndex: 2,
    paddingTop: 16,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 16px",
    background: "rgba(237, 233, 254, 0.68)",
    border: "1px solid rgba(99,102,241,0.12)",
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 600,
    color: "#6366F1",
    marginBottom: 28,
  },
  h1: {
    fontSize: "clamp(56px, 6vw, 88px)",
    fontWeight: 800,
    lineHeight: 1.02,
    color: "#07133F",
    letterSpacing: "-0.045em",
    marginBottom: 28,
  },
  h1Dot: {
    color: "#FF6B8E",
    fontWeight: 900,
  },
  sub: {
    fontSize: 18,
    lineHeight: 1.7,
    color: "#56637B",
    marginBottom: 40,
    maxWidth: 460,
  },
  ctaRow: {
    display: "flex",
    alignItems: "center",
    gap: 20,
    marginBottom: 14,
    flexWrap: "wrap",
  },
  mobileCta: {
    display: "none",
    flexDirection: "column",
    alignItems: "flex-start",
    position: "relative",
    zIndex: 2,
  },
  ctaPrimary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "18px 34px",
    background: "linear-gradient(135deg, #4F46E5 0%, #4338CA 100%)",
    color: "#fff",
    textDecoration: "none",
    fontWeight: 700,
    fontSize: 18,
    borderRadius: 18,
    boxShadow: "0 16px 32px rgba(79,70,229,0.20)",
  },
  ctaSecondary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 12,
    padding: "6px 0",
    color: "#131B3F",
    textDecoration: "none",
    fontWeight: 500,
    fontSize: 18,
  },
  noCc: {
    fontSize: 14,
    color: "#7C869A",
    marginBottom: 0,
  },

  /* Sections */
  section: {
    maxWidth: 1000,
    margin: "0 auto",
    padding: "96px 48px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
  },
  sectionAlt: {
    maxWidth: "100%",
    padding: "96px 48px",
    background: "#F0EEFF",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    color: "#6366F1",
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: "clamp(28px, 4vw, 44px)",
    fontWeight: 800,
    color: "#111827",
    letterSpacing: "-0.02em",
    marginBottom: 48,
    lineHeight: 1.15,
  },

  /* Steps */
  steps: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 24,
    width: "100%",
    maxWidth: 900,
  },
  stepCard: {
    background: "#fff",
    border: "1px solid rgba(99,102,241,0.10)",
    borderRadius: 20,
    padding: "32px 28px",
    textAlign: "left",
    boxShadow: "0 2px 16px rgba(99,102,241,0.05)",
  },
  stepNum: {
    fontSize: 13,
    fontWeight: 800,
    color: "#6366F1",
    letterSpacing: "0.1em",
    display: "block",
    marginBottom: 14,
  },
  stepTitle: {
    fontSize: 22,
    fontWeight: 800,
    color: "#111827",
    marginBottom: 12,
    letterSpacing: "-0.02em",
  },
  stepBody: { fontSize: 15, color: "#6B7280", lineHeight: 1.7 },

  /* Use cases */
  useCaseGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 20,
    width: "100%",
    maxWidth: 900,
  },
  useCaseCard: {
    background: "#fff",
    border: "1px solid rgba(99,102,241,0.12)",
    borderRadius: 20,
    padding: "28px 24px",
    textAlign: "left",
    boxShadow: "0 2px 12px rgba(99,102,241,0.05)",
  },
  useCaseIcon: { fontSize: 28, display: "block", marginBottom: 12 },
  useCaseTitle: { fontSize: 18, fontWeight: 700, color: "#111827", marginBottom: 14 },
  useCaseList: { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 10 },
  useCaseItem: {
    fontSize: 14,
    color: "#6B7280",
    lineHeight: 1.6,
    paddingLeft: 16,
    borderLeft: "2px solid #EDE9FE",
    fontStyle: "italic",
  },

  /* Pricing */
  pricingBody: {
    fontSize: 17,
    color: "#6B7280",
    maxWidth: 480,
    lineHeight: 1.7,
    marginBottom: 32,
    textAlign: "center",
  },

  /* Final CTA */
  ctaSection: { padding: "0 48px", display: "flex", justifyContent: "center" },
  ctaBox: {
    width: "100%",
    maxWidth: 680,
    background: "linear-gradient(135deg, #6366F1, #7C3AED)",
    borderRadius: 28,
    padding: "64px 48px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    margin: "80px 0",
    boxShadow: "0 24px 80px rgba(99,102,241,0.30)",
  },
  ctaTitle: {
    fontSize: "clamp(28px, 4vw, 40px)",
    fontWeight: 800,
    color: "#fff",
    letterSpacing: "-0.02em",
    marginBottom: 12,
    lineHeight: 1.15,
  },
  ctaSub: { fontSize: 18, color: "rgba(255,255,255,0.75)", marginBottom: 32 },
  ctaPrimaryLarge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "16px 36px",
    background: "#fff",
    color: "#6366F1",
    textDecoration: "none",
    fontWeight: 800,
    fontSize: 17,
    borderRadius: 14,
    boxShadow: "0 4px 24px rgba(0,0,0,0.15)",
  },

  /* Footer */
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 16,
    padding: "28px 48px",
    borderTop: "1px solid rgba(0,0,0,0.07)",
    background: "#F8F7FF",
  },
  footerLogo: { display: "flex", alignItems: "center", gap: 8, textDecoration: "none" },
  footerLogoText: { fontSize: 16, fontWeight: 700, color: "#111827" },
  footerLinks: { display: "flex", gap: 24 },
  footerLink: { fontSize: 14, color: "#6B7280", textDecoration: "none" },
  footerCopy: { fontSize: 13, color: "#9CA3AF" },
};