import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--color-bg)",
    padding: "24px",
  },
  card: {
    width: "100%",
    maxWidth: 400,
    background: "var(--color-card)",
    borderRadius: 24,
    padding: "40px 32px",
    boxShadow: "0 8px 48px rgba(99, 102, 241, 0.10)",
    border: "1px solid var(--color-border)",
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 28,
  },
  logoIcon: {
    width: 36,
    height: 36,
    borderRadius: 9,
    objectFit: "cover",
  },
  logoText: {
    fontSize: 22,
    fontWeight: 700,
    background: "linear-gradient(90deg, #6366F1, #F59E0B)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  heading: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 6,
    color: "var(--color-text)",
  },
  subtext: {
    fontSize: 15,
    color: "var(--color-text-secondary)",
    marginBottom: 28,
  },
  errorBox: {
    background: "#FEF2F2",
    border: "1px solid #FECACA",
    borderRadius: 10,
    padding: "12px 14px",
    color: "#DC2626",
    fontSize: 14,
    marginBottom: 16,
  },
  socialBtn: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "13px 16px",
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    marginBottom: 10,
    transition: "opacity 0.15s",
  },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    background: "var(--color-border)",
  },
  dividerText: {
    fontSize: 13,
    color: "var(--color-text-muted)",
    whiteSpace: "nowrap",
  },
  input: {
    width: "100%",
    padding: "13px 14px",
    border: "1.5px solid var(--color-border-strong)",
    borderRadius: 12,
    fontSize: 15,
    color: "var(--color-text)",
    background: "#FAFAFA",
    marginBottom: 10,
    outline: "none",
    transition: "border-color 0.15s, box-shadow 0.15s",
    display: "block",
  },
  submitBtn: {
    width: "100%",
    padding: "13px 16px",
    background: "linear-gradient(135deg, #6366F1, #7C3AED)",
    border: "none",
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 600,
    color: "#fff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    transition: "opacity 0.15s",
  },
  linkSentBox: {
    textAlign: "center",
    padding: "28px 20px",
    background: "var(--color-primary-light)",
    borderRadius: 16,
    marginBottom: 4,
  },
  linkSentBack: {
    marginTop: 16,
    color: "var(--color-primary)",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
  },
  legal: {
    marginTop: 24,
    fontSize: 12,
    color: "var(--color-text-muted)",
    textAlign: "center",
    lineHeight: 1.5,
  },
};